require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ZimboCharades' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNDeviceRotation', :path => '../node_modules/react-native-device-rotation'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNRate', :path => '../node_modules/react-native-rate'

  pod 'RNPaypal', :path => '../node_modules/react-native-paypal-lib'

  pod 'react-native-admob', :path => '../node_modules/react-native-admob'

  target 'ZimboCharadesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ZimboCharades-tvOS' do
  # Pods for ZimboCharades-tvOS

  target 'ZimboCharades-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
